# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:30
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0004_message_reference_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='reference_id',
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=hashid_field.field.HashidAutoField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', min_length=7, primary_key=True, serialize=False),
        ),
    ]
