# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-25 20:39
from __future__ import unicode_literals

from django.db import migrations
import hashid_field.field


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0005_auto_20170125_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reference_id',
            field=hashid_field.field.HashidField(alphabet='abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890', default=1, min_length=7),
            preserve_default=False,
        ),
    ]
